import { type Metadata } from 'next'

import { type Dictionary, t } from 'intlayer'

const homePageMetadata = {
  key: 'home-page-metadata',
  content: {
    title: t({
      en: 'Create Next App',
      es: 'Crear una aplicación Next.js',
    }),
    description: t({
      en: 'Generated by create next app',
      es: 'Generado por create next app',
    }),
  },
} satisfies Dictionary<Metadata>

export default homePageMetadata
